### PR TITLE
Allow `authGSSClientInit` principal kwarg to be None.

### LINKED ISSUE #49: authGSSClientInit no longer accepts None for principal
*dcallagh@…* originally submitted this as *[ticket:942](https://trac.calendarserver.org/ticket/942)*

---

In [r13269](https://trac.calendarserver.org/changeset/13269) the argument parsing for authGSSClientInit was (accidentally?) changed to no longer accept None for the principal argument.

This breaks the requests-kerberos module: <https://github.com/requests/requests-kerberos/issues/76>

Fix is trivial, change `s` back to `z` in the argument format string.

### PR DESCRIPTION
**Pull request by kwlzn**
This PR simply applies the patch from https://github.com/apple/ccs-pykerberos/issues/49 for easier merging.

Fixes #49

### CODE REVIEW

**Comment by dreness** [comment]
Hi @kwlzn 

We don't yet have any automated tests hooked up for this project. Some of the included tests require admin-level access to a kerberized service of some variety. If you happen to have such a configuration at your disposal, would you mind running through the included tests (with your patch applied) and posting your results?

I just added some [testing notes](https://github.com/apple/ccs-pykerberos/blob/master/testing_notes.md) to clarify how the tests are used, and the requirements / preconditions for each. Normally I wouldn't ask you to do this, but since I don't have an environment handy for this, and since you asked for expediting, this might be a chance to speed things along a bit. If not, that's fine too, I will just need to set up a test environment (which shouldn't take all that long...).

**Comment by kwlzn** [comment]
@dreness I unfortunately do not have admin-level access within our infra, sorry. :(

**Comment by dreness** [comment]
Just spent a lot of hours trying to get the tests to run against a system which I am now declaring to be too complicated for this purpose (apple's Server.app web service). I will try to find the simplest docker thing that I can find instead; unfortunately I don't remember exactly what I used last time.

**Comment by cyrusdaboo** [comment]
This change looks OK to me.

**Pull request merged**
