### PR TITLE
Add Travis-CI Test Integration

### PR DESCRIPTION
**Pull request by jborean93**
Added a test suite to setup a Kerberos system in a container and run the 4 existing tests in this environment. The tests themselves have been cleaned up to either simplify them and/or throw exceptions if they fail instead of just outputting errors to the console.

### CODE REVIEW

**Comment by jborean93** [comment]
@dreness @cyrusdaboo @m0rgen I was getting sick of trying to set up an environment to test this in and wanted to try out a few things. Please let me know your thoughts on this and whether you have any concerns or things you wish to change. I can confirm the tests are passing as shown by this page https://travis-ci.org/jborean93/ccs-pykerberos

FYI @Lukasa @behackett @rbcarson once this is through I will probably be looking at adding a similar setup to requests-kerberos for automated tests.

**Comment by jborean93** [comment]
The `{$KERBEROS_HOST^^}` means to convert the variable `KERBEROS_HOST` to upper case as shown [here](https://stackoverflow.com/questions/2264428/converting-string-to-lower-case-in-bash-shell-scripting). I believe you need Bash 4.0 and higher for this to work and in the context of the container this is there. As the .travis.yml script sets `KERBEROS_HOST` to a lower case `example.com` we need to use the upper case `EXAMPLE.COM` instead.

For the different Python versions I'm not aware of a way of using apt-get to specify a specific Python version, I believe you can state Python 2 and Python 3 but not a specific version in each variant. As it is the longest part of the test script I would happily change it if proven otherwise but a quick Google search isn't showing me any options.

**Comment by dreness** [comment]
Ah, indeed it is a bash4 feature:

```
bash-4.4$ KERBEROS_HOSTNAME="foci.local"
bash-4.4$ echo ${KERBEROS_HOSTNAME^^}
FOCI.LOCAL
```

The prospect of the script having various expansion errors and yet still yielding the expected result was somewhat mind-bending, even though I apparently managed to convince myself it was possible.

On the topic of getting binaries for various Python versions: there's an apt for that - [ppa:fkrull/deadsnakes](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes). However, this isn't "official" (although it is [whitelisted by Travis](https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json#L84) for use in 'restricted' environments), and doesn't have all the versions you've specified anyway. So I guess stick with the current strategy.

**Comment by dreness** [comment]
Thanks for this, @jborean93! I've enabled this project on the travis side with the following options enabled:

* Build only if .travis.yml is present
* Build branch updates
* Build pull request updates

**Comment by jborean93** [comment]
Hey @dreness looks like this will fail due it now using set -e, you may want to revert this change until I get it working again sorrry.

**Comment by dreness** [comment]
Hah, yeah... that would be my fault for not checking the [result of the travis build on your fork](https://github.com/jborean93/ccs-pykerberos/commits/travis-ci)...

I think I can just re-open this PR. Since the travis failure shouldn't have any adverse effect on the functioning of pykerberos itself, I think we can forgo reverting it from master since I see you're working on fixing it...

**Comment by jborean93** [comment]
Cool, the latest code has been committed and should be all working now, thanks for your help.

**Pull request merged**
